# Generated by Django 6.0.7 on 2026-07-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('logo', models.ImageField(help_text='Usar PNG transparente o WebP.', upload_to='clientes/', verbose_name='Logo del Cliente')),
                ('enlace', models.URLField(blank=True, help_text='Enlace a la web del cliente (Opcional)', null=True, verbose_name='Enlace web')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Servicio')),
                ('slug', models.SlugField(help_text='Se genera automáticamente a partir del título.', unique=True, verbose_name='URL Slug')),
                ('descripcion_corta', models.TextField(help_text='Texto breve que aparece en las tarjetas de la página de inicio.', max_length=255, verbose_name='Descripción Corta')),
                ('descripcion_larga', models.TextField(help_text='Texto completo que aparece en el detalle del servicio.', verbose_name='Descripción Larga')),
                ('icono', models.FileField(blank=True, help_text='Opcional. Icono representativo.', null=True, upload_to='servicios/iconos/', verbose_name='Icono (SVG/PNG)')),
                ('imagen_banner', models.ImageField(help_text='Imagen principal del servicio.', upload_to='servicios/banners/', verbose_name='Imagen Banner')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (0 es el primero).', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, help_text='Si está desmarcado, el servicio no aparecerá en la web.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='SitioConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_principal', models.CharField(default='+51 999 999 999', max_length=20, verbose_name='Teléfono Principal')),
                ('whatsapp', models.CharField(default='51999999999', help_text='Ej. 51999999999', max_length=20, verbose_name='WhatsApp (Solo números)')),
                ('correo_contacto', models.EmailField(default='operaciones@jht.com', max_length=254, verbose_name='Correo de Contacto')),
                ('direccion', models.TextField(default='Av. Ejemplo 123, Lima, Perú', verbose_name='Dirección Física')),
                ('enlace_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('enlace_linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('enlace_instagram', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('texto_footer', models.TextField(blank=True, default='Expertos en logística y transporte a nivel nacional.', verbose_name='Texto corto Footer')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
        migrations.CreateModel(
            name='VehiculoFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Furgón 2 Toneladas', max_length=100, verbose_name='Nombre del Vehículo')),
                ('categoria', models.CharField(choices=[('liviana', 'Flota Liviana'), ('mediana', 'Flota Mediana'), ('pesada', 'Flota Pesada')], default='liviana', max_length=20, verbose_name='Categoría')),
                ('capacidad_carga', models.CharField(help_text='Ej. 1.5 a 3 Toneladas', max_length=50, verbose_name='Capacidad de Carga')),
                ('capacidad_volumen', models.CharField(help_text='Ej. 15 a 20 m3', max_length=50, verbose_name='Capacidad de Volumen')),
                ('descripcion', models.TextField(help_text='Breve descripción del vehículo y su uso ideal.', verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='flota/', verbose_name='Imagen del Vehículo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Vehículo de Flota',
                'verbose_name_plural': 'Vehículos de Flota',
                'ordering': ['categoria', 'orden'],
            },
        ),
    ]
