# Generated by Django 6.0.7 on 2026-07-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(max_length=255, verbose_name='Descripción')),
                ('icono', models.CharField(default='verified', help_text='Ej: schedule, gps_fixed, verified_user, public', max_length=50, verbose_name='Nombre del Ícono (Google Material Symbols)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PasoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='El número que aparece en el círculo.', unique=True, verbose_name='Paso Número')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(max_length=255, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Paso de Trabajo',
                'verbose_name_plural': 'Pasos de Trabajo',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255, verbose_name='Pregunta')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SeccionLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('HERO', 'Sección Principal (Hero)'), ('BENEFICIOS', 'Sección Beneficios'), ('PROCESO', 'Sección Cómo Trabajamos'), ('NOSOTROS', 'Sección Sobre Nosotros'), ('COBERTURA', 'Sección Cobertura Nacional'), ('CTA', 'Llamada a la acción (CTA final)')], max_length=20, unique=True, verbose_name='Sección')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título Principal')),
                ('subtitulo', models.TextField(blank=True, verbose_name='Subtítulo o Descripción corta')),
                ('imagen', models.ImageField(blank=True, help_text='Para secciones como Nosotros o Cobertura.', null=True, upload_to='landing/imagenes/', verbose_name='Imagen')),
                ('video_url', models.FileField(blank=True, help_text='Para el fondo del Hero o Cobertura.', null=True, upload_to='landing/videos/', verbose_name='Video (MP4)')),
                ('activo', models.BooleanField(default=True, verbose_name='Mostrar Sección')),
            ],
            options={
                'verbose_name': 'Sección de Landing',
                'verbose_name_plural': 'Secciones de Landing',
            },
        ),
    ]
