# Generated by Django 6.0.7 on 2026-07-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_beneficio_pasotrabajo_preguntafrecuente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionlanding',
            name='seccion',
            field=models.CharField(choices=[('HERO', 'Sección Principal (Hero)'), ('SERVICIOS', 'Sección Servicios'), ('FLOTA', 'Sección Nuestra Flota'), ('BENEFICIOS', 'Sección Beneficios'), ('PROCESO', 'Sección Cómo Trabajamos'), ('NOSOTROS', 'Sección Sobre Nosotros'), ('CLIENTES', 'Sección Empresas (Clientes)'), ('COBERTURA', 'Sección Cobertura Nacional'), ('CTA', 'Llamada a la acción (CTA final)')], max_length=20, unique=True, verbose_name='Sección'),
        ),
    ]
