# Generated by Django 6.0.7 on 2026-07-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_seccionlanding_seccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beneficio',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='PasoTrabajo',
        ),
        migrations.DeleteModel(
            name='PreguntaFrecuente',
        ),
        migrations.DeleteModel(
            name='SeccionLanding',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='SitioConfiguracion',
        ),
        migrations.DeleteModel(
            name='VehiculoFlota',
        ),
    ]
