# Generated by Django 6.0.7 on 2026-07-29 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0004_delete_beneficio_delete_cliente_delete_pasotrabajo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bloque', models.CharField(choices=[('HERO', 'Hero Banner Principal'), ('GRID_SERVICIOS', 'Catálogo: Grid de Servicios'), ('GRID_FLOTA', 'Catálogo: Grid de Vehículos'), ('GRID_TARJETAS', 'Sección: Grid de Tarjetas (Beneficios, Pasos)'), ('CARRUSEL_LOGOS', 'Sección: Carrusel de Logos (Clientes)'), ('ACORDEON', 'Sección: Acordeón (Preguntas Frecuentes)'), ('TEXTO_IMAGEN', 'Sección: Texto e Imagen Alternada')], max_length=30, verbose_name='Tipo de Componente')),
                ('titulo', models.CharField(blank=True, help_text='Aparece arriba del bloque.', max_length=200, verbose_name='Título de la Sección')),
                ('subtitulo', models.TextField(blank=True, verbose_name='Subtítulo')),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='bloques/imagenes/', verbose_name='Imagen de Fondo')),
                ('video_fondo', models.FileField(blank=True, null=True, upload_to='bloques/videos/', verbose_name='Video de Fondo (MP4)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='Mostrar Bloque')),
            ],
            options={
                'verbose_name': 'Bloque de Sección',
                'verbose_name_plural': '2. Bloques de Sección',
                'ordering': ['pagina', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_principal', models.CharField(default='+51 999 999 999', max_length=50, verbose_name='Teléfono Principal')),
                ('whatsapp', models.CharField(default='51999999999', max_length=30, verbose_name='WhatsApp (Solo números para API)')),
                ('correo_contacto', models.EmailField(default='operaciones@jht.com', max_length=254, verbose_name='Correo de Contacto')),
                ('direccion', models.TextField(default='Lima, Perú', verbose_name='Dirección Física')),
                ('enlace_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('enlace_linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('texto_footer', models.TextField(blank=True, verbose_name='Texto corto Footer')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': '6. Configuración Global',
            },
        ),
        migrations.CreateModel(
            name='FlotaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Vehículo')),
                ('categoria', models.CharField(choices=[('LIVIANA', 'Flota Liviana'), ('MEDIANA', 'Flota Mediana'), ('PESADA', 'Flota Pesada')], default='LIVIANA', max_length=20, verbose_name='Categoría')),
                ('capacidad_carga', models.CharField(max_length=100, verbose_name='Capacidad de Carga')),
                ('capacidad_volumen', models.CharField(max_length=100, verbose_name='Capacidad de Volumen')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='catalogo/flota/', verbose_name='Imagen del Vehículo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Vehículo de Flota',
                'verbose_name_plural': '5. Catálogo de Flota',
                'ordering': ['categoria', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título de la Página')),
                ('slug', models.SlugField(blank=True, help_text="Ej: 'landing', 'nosotros'. Se genera automático.", unique=True, verbose_name='URL Slug')),
                ('meta_titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Meta Título (SEO)')),
                ('meta_descripcion', models.TextField(blank=True, null=True, verbose_name='Meta Descripción (SEO)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': '1. Páginas (Page Builder)',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Servicio')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Slug')),
                ('descripcion_corta', models.TextField(max_length=255, verbose_name='Descripción Corta')),
                ('descripcion_larga', models.TextField(verbose_name='Descripción Larga')),
                ('icono', models.FileField(blank=True, null=True, upload_to='catalogo/servicios/iconos/', verbose_name='Icono (SVG/PNG)')),
                ('imagen_banner', models.ImageField(upload_to='catalogo/servicios/banners/', verbose_name='Imagen Banner')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio Logístico',
                'verbose_name_plural': '4. Catálogo de Servicios',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ItemBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Para FAQs, aquí va la pregunta.', max_length=200, verbose_name='Título del Item')),
                ('descripcion', models.TextField(blank=True, help_text='Para FAQs, aquí va la respuesta.', verbose_name='Descripción / Contenido')),
                ('imagen_icono', models.FileField(blank=True, null=True, upload_to='bloques/items/', verbose_name='Imagen, Logo o Icono SVG')),
                ('enlace_url', models.URLField(blank=True, help_text='Opcional. Si la tarjeta o logo debe llevar a un link.', null=True, verbose_name='Enlace / Link')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden del Item')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.bloqueseccion', verbose_name='Bloque Contenedor')),
            ],
            options={
                'verbose_name': 'Item de Bloque',
                'verbose_name_plural': '3. Items de Bloques',
                'ordering': ['bloque', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='bloqueseccion',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='website.pagina', verbose_name='Página Perteneciente'),
        ),
    ]
