# Generated by Django 6.0.7 on 2026-07-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueseccion',
            name='tipo_bloque',
            field=models.CharField(choices=[('HERO', 'Hero Banner Principal'), ('NOSOTROS', 'Sección: Sobre Nosotros'), ('BENEFICIOS', 'Sección: Beneficios (Por qué elegirnos)'), ('PASOS', 'Sección: Cómo Trabajamos (Pasos)'), ('CARRUSEL_LOGOS', 'Sección: Carrusel de Clientes (Logos)'), ('ACORDEON', 'Sección: Acordeón (Preguntas Frecuentes)'), ('COBERTURA', 'Sección: Cobertura Nacional'), ('TEXTO_IMAGEN', 'Sección: Texto e Imagen (Genérico)')], max_length=30, verbose_name='Tipo de Componente'),
        ),
    ]
