# Generated by Django 6.0.7 on 2026-07-29 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_bloqueseccion_tipo_bloque'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloqueseccion',
            table='landing_bloqueseccion',
        ),
        migrations.AlterModelTable(
            name='configuracionglobal',
            table='landing_configuracionglobal',
        ),
        migrations.AlterModelTable(
            name='flotavehiculo',
            table='landing_flotavehiculo',
        ),
        migrations.AlterModelTable(
            name='itembloque',
            table='landing_itembloque',
        ),
        migrations.AlterModelTable(
            name='pagina',
            table='landing_pagina',
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='landing_servicio',
        ),
    ]
