# Generated by Django 6.0.7 on 2026-08-09 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrmContacto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono / Celular')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'crm_contacto',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='CrmSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen', models.CharField(choices=[('cotizacion', 'Cotización'), ('contacto_general', 'Contacto General')], max_length=50, verbose_name='Origen de la Solicitud')),
                ('servicio_interes', models.CharField(blank=True, choices=[('transporte-carga', 'Transporte de Carga'), ('distribucion', 'Distribución'), ('courier', 'Courier / Delivery Express'), ('mudanzas', 'Mudanzas'), ('carga-refrigerada', 'Carga Refrigerada'), ('almacenaje', 'Almacenaje'), ('personal-estiba', 'Personal de Estiba')], max_length=100, null=True, verbose_name='Servicio de Interés')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje o Requerimiento')),
                ('estado_ventas', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_proceso', 'En Proceso'), ('cotizado', 'Cotizado'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', max_length=20, verbose_name='Estado en Ventas')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='crm.crmcontacto', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'crm_solicitud',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
