# Generated by Django 6.0.7 on 2026-07-27 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre completo o Área')),
                ('cargo', models.CharField(blank=True, max_length=120, verbose_name='Cargo o Especialidad')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía corta')),
                ('imagen', models.ImageField(blank=True, help_text='Opcional. Foto cuadrada recomendada (200x200px).', null=True, upload_to='noticias/autores/', verbose_name='Foto del Autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'noticias_autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug URL')),
                ('color_badge', models.CharField(default='bg-jht-gold text-jht-dark', help_text='Clases Tailwind para el badge de categoría en la tarjeta. Ej: bg-jht-gold text-jht-dark', max_length=50, verbose_name='Clase CSS del Badge')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'noticias_categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug URL')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table': 'noticias_etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text='Se genera automáticamente desde el título. Es único y forma la URL del artículo.', max_length=220, unique=True, verbose_name='Slug URL')),
                ('bajada', models.TextField(help_text='Texto corto (≤320 caracteres) para la tarjeta de la lista y el meta description SEO.', max_length=320, verbose_name='Bajada / Resumen')),
                ('contenido_html', models.TextField(help_text='Cuerpo completo del artículo en formato HTML. Próximamente se integrará un editor visual (WYSIWYG).', verbose_name='Contenido del Artículo (HTML)')),
                ('imagen_portada', models.ImageField(help_text='Imagen principal del artículo. Recomendado: 1200x630px WebP.', upload_to='noticias/portadas/', verbose_name='Imagen de Portada')),
                ('imagen_cuerpo', models.ImageField(blank=True, help_text='Imagen opcional que aparece a mitad del artículo para romper el bloque de texto.', null=True, upload_to='noticias/cuerpo/', verbose_name='Imagen en el Cuerpo')),
                ('texto_imagen_cuerpo', models.CharField(blank=True, help_text='Descripción breve que aparece bajo la imagen del cuerpo del artículo.', max_length=200, verbose_name='Pie de foto (imagen cuerpo)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', help_text='Solo los artículos "Publicados" son visibles en la web.', max_length=12, verbose_name='Estado')),
                ('es_destacado', models.BooleanField(default=False, help_text='Si está marcado, aparece en la sección hero/principal de la página de Noticias.', verbose_name='¿Artículo Destacado?')),
                ('vistas', models.PositiveIntegerField(default=0, editable=False, help_text='Se incrementa automáticamente cada vez que alguien visita el artículo.', verbose_name='Contador de Vistas')),
                ('fecha_publicacion', models.DateTimeField(blank=True, help_text='Dejar vacío mientras sea borrador. Se puede programar publicación futura.', null=True, verbose_name='Fecha de Publicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('autor', models.ForeignKey(blank=True, help_text='SET_NULL: Si se borra el autor, el artículo queda sin autor (no se pierde).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='noticias.autor', verbose_name='Autor')),
                ('categoria', models.ForeignKey(help_text='PROTECT: No se puede borrar una categoría que tenga artículos asociados.', on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='noticias.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'noticias_articulos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=80, verbose_name='Nombre')),
                ('email_autor', models.EmailField(help_text='No se publica. Solo para contacto interno.', max_length=120, verbose_name='Email')),
                ('contenido', models.TextField(verbose_name='Comentario')),
                ('aprobado', models.BooleanField(default=False, help_text='Solo los comentarios aprobados son visibles en la web pública.', verbose_name='Aprobado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Enviado el')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticias.articulo', verbose_name='Artículo')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'noticias_comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.articulo')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.etiqueta')),
            ],
            options={
                'verbose_name': 'Etiqueta de Artículo',
                'verbose_name_plural': 'Etiquetas de Artículos',
                'db_table': 'noticias_articulos_etiquetas',
                'unique_together': {('articulo', 'etiqueta')},
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='articulos', through='noticias.ArticuloEtiqueta', to='noticias.etiqueta', verbose_name='Etiquetas'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['estado', '-fecha_publicacion'], name='idx_noticias_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['slug'], name='idx_noticias_slug'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['es_destacado'], name='idx_noticias_destacado'),
        ),
    ]
