# Generated by Django 6.0.7 on 2026-07-12 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='JHT Transport', max_length=100, verbose_name='Nombre de la Empresa')),
                ('email', models.EmailField(default='contacto@jht.com.pe', max_length=254, verbose_name='Correo de Contacto')),
                ('phone', models.CharField(default='+51 987 654 321', max_length=20, verbose_name='Teléfono')),
                ('address', models.CharField(default='Av. Principal 123, Distrito Logístico, Ciudad.', max_length=255, verbose_name='Dirección')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información de Empresa',
                'verbose_name_plural': 'Información de Empresa',
            },
        ),
        migrations.CreateModel(
            name='FleetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de Flota',
                'verbose_name_plural': 'Categorías de Flota',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título del Servicio')),
                ('slug', models.SlugField(help_text='URL amigable', unique=True, verbose_name='Slug')),
                ('icon_name', models.CharField(default='local_shipping', max_length=50, verbose_name='Icono (Material Symbols)')),
                ('short_description', models.TextField(max_length=200, verbose_name='Descripción Corta')),
                ('full_description', models.TextField(blank=True, verbose_name='Descripción Completa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/services/', verbose_name='Imagen Representativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre/Tipo de Vehículo')),
                ('capacity', models.CharField(help_text='Ej: Hasta 30 toneladas', max_length=100, verbose_name='Capacidad')),
                ('features', models.TextField(blank=True, help_text='Listado de características separadas por comas', verbose_name='Características')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/fleet/', verbose_name='Imagen del Vehículo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='cms.fleetcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
